### ISSUE TITLE
rule_1_2_6 custom fact not implemented

### ISSUE THREAD

**Issue by abuxton** [bossbear/cis_rhel7#12]
$::cis_benchmarks['pkg_integrity'] is not created as part of /lib/facter/cis_benchmark.rb
rule_1_2_6 expects this custom fact. 

Suggested fix due to the size of custom fact and load to run integrity check is to update the rule to deploy the script if the rule is set to true and run it on a none optional schedule that can be set in hiera, via a param on the rule.

**Comment by abuxton** [comment]
Preparing a Pull request with a patch https://github.com/abuxton/cis_rhel7/tree/issues12

**Comment by bossbear** [comment]
Thanks for suggesting a fix.  I'll welcome a PR so when you are ready please make the PR and I'll merge the fix.  Thanks again,

**Comment by bossbear** [comment]
closed as per PR #15
