### ISSUE TITLE
Add noop param on resource type

### ISSUE THREAD

**Issue by tux-o-matic** [bossbear/cis_rhel7#13]
Today, to get a compliance report, Puppet must be executed with the --noop flag.
This is not practical at scale, it would be easier with a boolean flag on the module which would control the noop meta parameter of the resource type.
For example:
```puppet
class cis_rhel7 (
  Boolean $noop_resource,
  [...]
) {
  File { noop => $noop_resource }
  Package { noop => $noop_resource }
  Service { noop => $noop_resource }

  [...]
}
```

**Comment by bossbear** [comment]
Thanks for the report.  I'll create an issue and will address the need.

**Comment by bossbear** [comment]
@tux-o-matic as you can see above, I’ve made some code changes that’ll address this issue.  Thanks for your participation.

**Comment by bossbear** [comment]
@tux-o-matic oh and new puppet module bossbear/cis_rhel7 version 0.9.12 has been published.
